[Interface]
PrivateKey = CK5UcxhfKduu0VHduTWAnJzedfwLPD+gbr8Uf3OqIk0=
Address = 192.168.188.204/24
DNS = 192.168.188.5,192.168.188.1
DNS = fritz.box

[Peer]
PublicKey = 3eFBxIJHyffWvdtPYbnBcDdFPDm6rlF+f2mxnAkj0y4=
PresharedKey = n7MNYCfNwU4FpKSSh143XGA9jz7iGEiruXqxo7tTS1o=
AllowedIPs = 192.168.188.0/24,0.0.0.0/0
Endpoint = bubatzpinguin.duckdns.org:51188
PersistentKeepalive = 25
